baseURL = "https://example.com"
title = "UNSWifties"
author = "UNSW Swiftie Society"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.png"
    alt = "UNSWifties Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-16"

  [params.site]
    name = "UNSWifties"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "The official website of the UNSW Taylor Swift Appreciation Society"
    meta_og_title = "UNSWifties"
    meta_og_type = "website"
    meta_og_url = "https://www.unswifties.org"
    meta_og_image = ""
    meta_og_description = "The official website of the UNSW Taylor Swift Appreciation Society"

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/UNSWifties/unswifties.github.io"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2
